package com.kylantis.eaa.core.forms;

public enum InputType {
	TEXT, EMAIL, SECRET, BOOLEAN, PHONE, DATE_OF_BIRTH, NUMBER, NUMBER_2L, NUMBER_3L, NUMBER_4L, AMOUNT, IMAGE, PLAIN, SIGNATURE, LANGUAGE, COUNTRY, TERRITORY, CITY
}
