package com.kylantis.eaa.core.keys;

public class MetricKeys {
	
	//DEPRECATED
	
	public static final String CUSTOMER_APPLICATION_COUNT_TIMESERIES = "CUSTOMER_APPLICATION_COUNT_TIMESERIES";
	public static final String CUSTOMER_APPLICATION_COUNT_CURRENT = "CUSTOMER_APPLICATION_COUNT_CURRENT";
	public static final String CUSTOMER_APPLICATION_COUNT_ARCHIVE = "CUSTOMER_APPLICATION_COUNT_ARCHIVE";
	
	public static final String USER_COUNT_TO_ROLE_$ROLE_CURRENT = "USER_COUNT_TO_ROLE_$ROLE_CURRENT";
	public static final String USER_COUNT_TO_ROLE_$ROLE_TIMESERIES = "USER_COUNT_TO_ROLE_$ROLE_TIMESERIES";
	
	public static final String USER_NAME_CHANGE_COUNT_$USER_CURRENT = "USER_NAME_CHANGE_COUNT_$USER_CURRENT";
	public static final String ENTITY_NAME_CHANGE_COUNT_$ENTITY_CURRENT = "HCP_NAME_CHANGE_COUNT_$ENTITY_CURRENT";

	public static final String USER_TO_APPLICATION_COUNT_$USER_ARCHIVE = "USER_TO_APPLICATION_COUNT_$USER_CURRENT";

	public static final String LAST_CREATED_ROLE_ID_$USER = "LAST_CREATED_ROLE_ID_$USER";
	
	public static final String EXTENSION_POINT_ELEMENT_COUNT_ARCHIVE = "EXTENSION_POINT_ELEMENT_COUNT_ARCHIVE";

	
	
	
	

	public static final String USERS_COUNT = "USERS_COUNT";
	
}
